# Generated by Django 3.1.7 on 2026-02-23 15:26

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommentReaction",
            fields=[
                ("datetime_created", models.DateTimeField(auto_now_add=True)),
                ("datetime_updated", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("author_id", models.IntegerField(db_index=True)),
                (
                    "reaction",
                    models.CharField(
                        choices=[
                            ("thumbs_up", "Thumbs Up"),
                            ("thumbs_down", "Thumbs Down"),
                            ("heart", "Heart"),
                            ("laugh", "Laugh"),
                            ("confused", "Confused"),
                            ("rocket", "Rocket"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="comments.comment",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="commentreaction",
            index=models.Index(
                fields=["comment", "reaction"], name="comments_co_comment_ecbfbf_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="commentreaction",
            unique_together={("comment", "author_id", "reaction")},
        ),
    ]
