# Generated by Django 5.2.16 on 2026-07-24 14:17

from django.db import migrations, models

import thunderstore.core.storage
import thunderstore.repository.models.package_version


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0065_delete_packageversiondownloadevent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="packageversion",
            name="file",
            field=models.FileField(
                storage=thunderstore.core.storage.get_package_storage,
                upload_to=thunderstore.repository.models.package_version.get_version_zip_filepath,
            ),
        ),
    ]
