# Generated by Django 5.2.16 on 2026-07-24 14:17

import thunderstore.core.storage
import thunderstore.modpacks.models.legacyprofile
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modpacks", "0003_add_checksum_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="legacyprofile",
            name="file",
            field=models.FileField(
                storage=thunderstore.core.storage.get_modpack_storage,
                upload_to=thunderstore.modpacks.models.legacyprofile.get_legacy_profile_file_path,
            ),
        ),
    ]
