# Generated by Django 5.2.16 on 2026-07-24 14:17

from django.db import migrations, models

import thunderstore.core.storage
import thunderstore.schema_server.models.file


class Migration(migrations.Migration):

    dependencies = [
        ("schema_server", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schemafile",
            name="data",
            field=models.FileField(
                blank=True,
                editable=False,
                null=True,
                storage=thunderstore.core.storage.get_schema_storage,
                upload_to=thunderstore.schema_server.models.file.get_schema_file_path,
            ),
        ),
    ]
