[tool.poetry]
name = "Thunderstore"
version = "0.0.0"
description = "Thunderstore is a mod database and API for downloading mods"
authors = ["Mythic <mythicmaniac@gmail.com>"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.14"
Django = ">=5.2.12,<5.3"
django-environ = "^0.14"
arrow = "^1.4"
Pillow = "^12.3"
psycopg2-binary = "^2.9.12"
easy-thumbnails = "^2.10.1"  # This has a monkeypatch and might be a difficult upgrade
gunicorn = { version = "^26.0", extras = ["gevent"] }
gevent = "^26.7"
uwsgi = "2.0.31"
social-auth-app-django = "^6.0"
social-auth-core = "^5.0.2"
whitenoise = "^6.12"
django-storages = { version = "^1.14.6", extras = ["boto3"] }
djangorestframework = "^3.17"
drf-yasg = "^1.21.15"
django-ipware = "^7.0"
sentry-sdk = { extras = ["celery"], version = "^2.66" }
django-redis = "^7.0"
pyjwt = { version = "^2.13", extras = ["crypto"] }
celery = "^5.6.3"
django-celery-results = "^2.6"
django-celery-beat = "^2.9"
ulid2 = "^0.3.0"
django-cachalot = "^2.9"
django-cors-headers = "^4.9"
boto3 = "^1.17.47"
nh3 = "^0.3.6"
markdown-it-py = { version = "^4.2", extras = ["linkify"] }
abyss = { git = "https://github.com/akx/abyss.git", rev = "4352e557f25a303f718ec1bf82ea0ca545ebc077" }
lxml = "^6.1"
pygments = "^2.20"
confluent-kafka = "^2.15"
pydantic = "^2.7"

[tool.poetry.group.plugins]
optional = true

[tool.poetry.group.plugins.dependencies]
django-paypal = { path = "../python-packages/django-paypal", develop = true }
paypal-api = { path = "../python-packages/paypal-api", develop = true }
ts-subsys = { path = "../python-packages/ts-subsys", develop = true }
ts-scanners = { path = "../python-packages/ts-scanners", develop = true }
ts-moderation = { path = "../python-packages/ts-moderation", develop = true }

[tool.poetry.group.dev.dependencies]
pytest = ">=9.0.3,<10"  # >=9.0.3 clears PYSEC-2026-1845 (local /tmp DoS)
pytest-cov = "^7.0"
pytest-django = "^4.12"
factory_boy = "^3.3"
Faker = "^40.0"
pytest-mock = "^3.14"
django-debug-toolbar = "^7.0"
pytest-env = "^1.7"
black = "^26.0"
isort = "^6.0"
jsonschema = "^4.23"
pre-commit = "^4.0"
mypy = ">=1.13,<2.2"
django-stubs = "^6.0.7"
djangorestframework-stubs = "^3.17"
flake8 = "^7.3"
flake8-2020 = "^1.8"
flake8-broken-line = "^1.0"
flake8-bugbear = "^25.11"
flake8-builtins = "^3.1"
flake8-commas = "^4.0"
flake8-comprehensions = "^3.17"
flake8-pie = "^0.16"
flake8-printf-formatting = "^1.1"
flake8-pytest-style = "^2.2"
pep8-naming = "^0.15"
watchdog = { extras = ["watchmedo"], version = "^6.0" }
mypy-boto3-s3 = "^1.43"
pytest-freezer = "^0.4.9"
pytest-xdist = "^3.8"
pytest-split = "^0.11"

[tool.black]
target-version = ["py314"]
exclude = '''
(
  /(
      \.git
    | \.mypy_cache
    | \.venv
    | \.vscode
    | \.idea
  )/
)
'''

[tool.isort]
profile = "black"
known_third_party = ["django"]

[build-system]
requires = ["poetry-core>=2.0"]
build-backend = "poetry.core.masonry.api"
