# Generated by Django 5.2.16 on 2026-07-24 16:04

import thunderstore.core.storage
import thunderstore.storage.models.blob
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0003_alter_datablob_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datablob",
            name="data",
            field=models.FileField(
                blank=True,
                editable=False,
                max_length=255,
                null=True,
                storage=thunderstore.core.storage.get_blob_storage,
                upload_to=thunderstore.storage.models.blob.get_object_file_path,
            ),
        ),
    ]
